<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2B - Linear Regression Solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="02B-Linear_regression - SOLUTIONS_files/libs/clipboard/clipboard.min.js"></script>
<script src="02B-Linear_regression - SOLUTIONS_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="02B-Linear_regression - SOLUTIONS_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="02B-Linear_regression - SOLUTIONS_files/libs/quarto-html/popper.min.js"></script>
<script src="02B-Linear_regression - SOLUTIONS_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="02B-Linear_regression - SOLUTIONS_files/libs/quarto-html/anchor.min.js"></script>
<link href="02B-Linear_regression - SOLUTIONS_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="02B-Linear_regression - SOLUTIONS_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="02B-Linear_regression - SOLUTIONS_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="02B-Linear_regression - SOLUTIONS_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="02B-Linear_regression - SOLUTIONS_files/libs/bootstrap/bootstrap-32c4765d3640e27ff663796585ccb24d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2B - Linear Regression Solutions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this document we will conduct linear regression modeling on a data set relating to graduate salaries in the United States, to try to understand economic factors which influence graduate salaries.</p>
<section id="exercise-1---running-a-simple-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1---running-a-simple-linear-regression-model">Exercise 1 - Running a simple linear regression model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Download the graduates dataset from the URL provided</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://peopleanalytics-regression-book.org/data/graduates.csv"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>graduates <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view the first few rows in the data set to acquaint yourself with the data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(graduates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  Major                      Discipline  Total
1                   GENERAL AGRICULTURE Agriculture &amp; Natural Resources 128148
2 AGRICULTURE PRODUCTION AND MANAGEMENT Agriculture &amp; Natural Resources  95326
3                AGRICULTURAL ECONOMICS Agriculture &amp; Natural Resources  33955
4                       ANIMAL SCIENCES Agriculture &amp; Natural Resources 103549
5                          FOOD SCIENCE Agriculture &amp; Natural Resources  24280
6            PLANT SCIENCE AND AGRONOMY Agriculture &amp; Natural Resources  79409
  Unemployment_rate Median_salary
1        0.02614711         50000
2        0.02863606         54000
3        0.03024832         63000
4        0.04267890         46000
5        0.04918845         62000
6        0.03179089         50000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine how many observations we have in this data set</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(graduates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 173</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use the colnames() function to get the names of the columns in the data set</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(graduates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Major"             "Discipline"        "Total"            
[4] "Unemployment_rate" "Median_salary"    </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the cor() function to determine the correlation between unemployment rate and median salary</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(graduates<span class="sc">$</span>Unemployment_rate, graduates<span class="sc">$</span>Median_salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.3019457</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Consider the scale of the Unemployment_rate column.  </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform it into a more useful scale</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (Hint: we will want to understand the impact of a percentage point change)</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>graduates<span class="sc">$</span>Unemployment_rate <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span>graduates<span class="sc">$</span>Unemployment_rate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a simple linear regression model to estimate the influence of unemployment rate</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># on graduate salaries, saving your model using a name of your choice</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> graduates, <span class="at">formula =</span> Median_salary <span class="sc">~</span> Unemployment_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercise-2---interpreting-the-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2---interpreting-the-coefficients">Exercise 2 - Interpreting the coefficients</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the coefficients of your saved model</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>model<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept) Unemployment_rate 
        70096.911         -2315.512 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine the 95% confidence interval for the coefficients</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      2.5 %    97.5 %
(Intercept)       63424.936 76768.887
Unemployment_rate -3419.067 -1211.958</code></pre>
</div>
</div>
<p>Write below an interpretation of these coefficients using the estimates and the confidence intervals which you just calculated.</p>
<ul>
<li>Unemployment rate has a statistically significant influence on median graduate salary</li>
<li>Full employment is associated with a median salary of between $63425 and $76769 on average</li>
<li>An additional percentage point in unemployment rate is associated with a reduction in median salary of between $1212 and $3419 on average</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># EXTENSION:  If you are familiar with using ggplot2, create a plot of unemployment rate and</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># median salary and show the estimated linear model using geom_smooth()</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> graduates, <span class="fu">aes</span>(<span class="at">x =</span> Unemployment_rate, <span class="at">y =</span> Median_salary)) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Unemployment rate (%)"</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Median salary ($)"</span>) <span class="sc">+</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02B-Linear_regression---SOLUTIONS_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exercise-3---running-a-multiple-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3---running-a-multiple-linear-regression-model">Exercise 3 - Running a multiple linear regression model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a multiple linear regression to determine the influence of both unemployment rate</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and total graduate employees on median salary</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Median_salary <span class="sc">~</span> Unemployment_rate <span class="sc">+</span> Total, graduates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the coefficients and confidence intervals</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>model2<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept) Unemployment_rate             Total 
     7.069198e+04     -2.343223e+03     -1.894123e-03 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          2.5 %        97.5 %
(Intercept)        6.382648e+04  7.755749e+04
Unemployment_rate -3.450722e+03 -1.235725e+03
Total             -6.926153e-03  3.137908e-03</code></pre>
</div>
</div>
<p>Write below an interpretation of the coefficients of this model.</p>
</section>
<section id="exercise-4---including-categorical-input-variables" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4---including-categorical-input-variables">Exercise 4 - Including categorical input variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add discipline as an input variable to the previous model you created in </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3.  </span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Median_salary <span class="sc">~</span> Unemployment_rate <span class="sc">+</span> Total <span class="sc">+</span> Discipline, </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>             graduates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect the results and determine which value was used as a reference for </span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># discipline in the model</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                      2.5 %        97.5 %
(Intercept)                                    5.309890e+04  6.715682e+04
Unemployment_rate                             -2.248705e+03 -3.458837e+02
Total                                         -3.647491e-03  3.819117e-03
DisciplineArts                                -1.528832e+04  4.772593e+03
DisciplineBiology &amp; Life Science              -1.064108e+04  4.968144e+03
DisciplineBusiness                            -9.672146e+02  1.595158e+04
DisciplineCommunications &amp; Journalism         -1.324829e+04  9.850149e+03
DisciplineComputers &amp; Mathematics              5.439571e+03  2.224382e+04
DisciplineEducation                           -1.788046e+04 -2.630368e+03
DisciplineEngineering                          1.724532e+04  3.113145e+04
DisciplineHealth                              -5.639558e+03  1.050717e+04
DisciplineHumanities &amp; Liberal Arts           -1.326690e+04  3.142300e+03
DisciplineIndustrial Arts &amp; Consumer Services -9.302614e+03  9.497455e+03
DisciplineInterdisciplinary                   -2.703539e+04  1.282003e+04
DisciplineLaw &amp; Public Policy                 -9.150384e+03  1.206888e+04
DisciplinePhysical Sciences                    8.546786e+02  1.782305e+04
DisciplinePsychology &amp; Social Work            -1.486827e+04  3.889056e+03
DisciplineSocial Science                      -7.424027e+03  1.060487e+04</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view all unique values for discipline</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(graduates<span class="sc">$</span>Discipline)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Agriculture &amp; Natural Resources"     "Biology &amp; Life Science"             
 [3] "Engineering"                         "Humanities &amp; Liberal Arts"          
 [5] "Communications &amp; Journalism"         "Computers &amp; Mathematics"            
 [7] "Industrial Arts &amp; Consumer Services" "Education"                          
 [9] "Law &amp; Public Policy"                 "Interdisciplinary"                  
[11] "Health"                              "Social Science"                     
[13] "Physical Sciences"                   "Psychology &amp; Social Work"           
[15] "Arts"                                "Business"                           </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># it appears that the first discipline in alphabetical order has been used</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># as reference (Agriculture &amp; Natural Resources)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Write below your thoughts on whether any specific disciplines have a significant influence on median salary.</p>
<p>Compared to a reference discipline of Agriculture &amp; Natural Resources, the following disciplines have a significant positive influence on median salary (assuming similar unemployment rates and total graduate numbers):</p>
<ul>
<li>Computers &amp; Mathematics (Yay for R programmers!)</li>
<li>Engineering</li>
<li>Physical Sciences</li>
</ul>
<p>and the following have a significant negative influence:</p>
<ul>
<li>Education</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># EXTENSION:  Change your reference discipline to a discipline of your choice,</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># rerun the model and inspect the results.  How have they changed?</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>graduates<span class="sc">$</span>Discipline <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(graduates<span class="sc">$</span>Discipline) <span class="sc">|&gt;</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relevel</span>(<span class="at">ref =</span> <span class="st">"Computers &amp; Mathematics"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Median_salary <span class="sc">~</span> Unemployment_rate <span class="sc">+</span> Total <span class="sc">+</span> Discipline, </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>             graduates)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                      2.5 %        97.5 %
(Intercept)                                    6.590542e+04  8.203370e+04
Unemployment_rate                             -2.248705e+03 -3.458837e+02
Total                                         -3.647491e-03  3.819117e-03
DisciplineAgriculture &amp; Natural Resources     -2.224382e+04 -5.439571e+03
DisciplineArts                                -2.820131e+04 -9.997809e+03
DisciplineBiology &amp; Life Science              -2.427128e+04 -9.085053e+03
DisciplineBusiness                            -1.432016e+04  1.621136e+03
DisciplineCommunications &amp; Journalism         -2.655835e+04 -4.523188e+03
DisciplineEducation                           -3.152224e+04 -1.667198e+04
DisciplineEngineering                          3.671058e+03  1.702232e+04
DisciplineHealth                              -1.929639e+04 -3.519399e+03
DisciplineHumanities &amp; Liberal Arts           -2.639708e+04 -1.141091e+04
DisciplineIndustrial Arts &amp; Consumer Services -2.278212e+04 -4.706431e+03
DisciplineInterdisciplinary                   -4.054532e+04 -1.353428e+03
DisciplineLaw &amp; Public Policy                 -2.249663e+04 -2.268268e+03
DisciplinePhysical Sciences                   -1.268773e+04  3.682062e+03
DisciplinePsychology &amp; Social Work            -2.792243e+04 -1.074018e+04
DisciplineSocial Science                      -2.069284e+04 -3.809716e+03</code></pre>
</div>
</div>
<p>Because we have referenced on one of the higher salary disciplines, we now see a lot more disciplines which have a significantly negative influence on median salary.</p>
</section>
<section id="exercise-5---determining-model-fit" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5---determining-model-fit">Exercise 5 - Determining model fit</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine the fit of your model from Exercise 4 </span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.626935</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine if any of the input variables can be removed to form a</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># more parsimonious model</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># we know from Exercise 4 that we can remove Total </span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Median_salary <span class="sc">~</span> Unemployment_rate <span class="sc">+</span> Discipline, graduates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify that these is no substantial difference in the fit of your</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># more parsimonious model</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6269301</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a summary of your parsimonious model </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Median_salary ~ Unemployment_rate + Discipline, 
    data = graduates)

Residuals:
   Min     1Q Median     3Q    Max 
-18681  -5185   -665   3455  47871 

Coefficients:
                                              Estimate Std. Error t value
(Intercept)                                    74001.1     4010.1  18.454
Unemployment_rate                              -1300.3      475.7  -2.734
DisciplineAgriculture &amp; Natural Resources     -13856.0     4228.1  -3.277
DisciplineArts                                -19085.7     4582.8  -4.165
DisciplineBiology &amp; Life Science              -16686.7     3827.0  -4.360
DisciplineBusiness                             -6299.8     3871.1  -1.627
DisciplineCommunications &amp; Journalism         -15513.1     5526.3  -2.807
DisciplineEducation                           -24089.6     3743.1  -6.436
DisciplineEngineering                          10340.8     3366.1   3.072
DisciplineHealth                              -11404.3     3979.8  -2.866
DisciplineHumanities &amp; Liberal Arts           -18893.5     3774.1  -5.006
DisciplineIndustrial Arts &amp; Consumer Services -13745.8     4560.5  -3.014
DisciplineInterdisciplinary                   -20954.1     9887.7  -2.119
DisciplineLaw &amp; Public Policy                 -12378.4     5102.9  -2.426
DisciplinePhysical Sciences                    -4509.4     4127.7  -1.092
DisciplinePsychology &amp; Social Work            -19320.8     4329.0  -4.463
DisciplineSocial Science                      -12238.0     4249.7  -2.880
                                              Pr(&gt;|t|)    
(Intercept)                                    &lt; 2e-16 ***
Unemployment_rate                              0.00699 ** 
DisciplineAgriculture &amp; Natural Resources      0.00129 ** 
DisciplineArts                                5.14e-05 ***
DisciplineBiology &amp; Life Science              2.35e-05 ***
DisciplineBusiness                             0.10567    
DisciplineCommunications &amp; Journalism          0.00564 ** 
DisciplineEducation                           1.44e-09 ***
DisciplineEngineering                          0.00251 ** 
DisciplineHealth                               0.00474 ** 
DisciplineHumanities &amp; Liberal Arts           1.49e-06 ***
DisciplineIndustrial Arts &amp; Consumer Services  0.00301 ** 
DisciplineInterdisciplinary                    0.03566 *  
DisciplineLaw &amp; Public Policy                  0.01642 *  
DisciplinePhysical Sciences                    0.27631    
DisciplinePsychology &amp; Social Work            1.54e-05 ***
DisciplineSocial Science                       0.00454 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9432 on 156 degrees of freedom
Multiple R-squared:  0.6269,    Adjusted R-squared:  0.5887 
F-statistic: 16.38 on 16 and 156 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The <span class="math inline">\(p\)</span>-value of the F-statistic is very small, indicating high confidence that the model is better than a null model.</p>
</section>
<section id="extension-exercise-6---model-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="extension-exercise-6---model-diagnostics">EXTENSION Exercise 6 - Model diagnostics</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine if the two numerical input variables have a significant correlation</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(graduates<span class="sc">$</span>Unemployment_rate, graduates<span class="sc">$</span>Total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  graduates$Unemployment_rate and graduates$Total
t = -0.87117, df = 171, p-value = 0.3849
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.21355488  0.08355632
sample estimates:
        cor 
-0.06647261 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the package mctest, use the imcdiag() function to test if collinearity </span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co"># exists in your full model from Exercise 3.  Use the VIF method for this.</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mctest)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>mctest<span class="sc">::</span><span class="fu">imcdiag</span>(model3, <span class="at">method =</span> <span class="st">"VIF"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mctest::imcdiag(mod = model3, method = "VIF")


 VIF Multicollinearity Diagnostics

                                                 VIF detection
Unemployment_rate                             1.6389         0
Total                                         1.2223         0
DisciplineAgriculture &amp; Natural Resources     1.9038         0
DisciplineArts                                1.8092         0
DisciplineBiology &amp; Life Science              2.1234         0
DisciplineBusiness                            2.1863         0
DisciplineCommunications &amp; Journalism         1.3576         0
DisciplineEducation                           2.2914         0
DisciplineEngineering                         3.0790         0
DisciplineHealth                              1.9891         0
DisciplineHumanities &amp; Liberal Arts           2.2016         0
DisciplineIndustrial Arts &amp; Consumer Services 1.5704         0
DisciplineInterdisciplinary                   1.0928         0
DisciplineLaw &amp; Public Policy                 1.4217         0
DisciplinePhysical Sciences                   1.8067         0
DisciplinePsychology &amp; Social Work            1.8024         0
DisciplineSocial Science                      1.7402         0

NOTE:  VIF Method Failed to detect multicollinearity


0 --&gt; COLLINEARITY is not detected by the test

===================================</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View a density plot of the Median salaries in the data set - what do you observe?</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">density</span>(graduates<span class="sc">$</span>Median_salary) <span class="sc">|&gt;</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="at">main =</span> <span class="st">"Median Salary Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02B-Linear_regression---SOLUTIONS_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution appears to be somewhat left-skewed due to a tail of high median salaries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use the qqnorm() function to determine how the residuals of your model </span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># compare to a normal distribution</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="co"># comment on your observations</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># consider re-running your model to address any concerns you have</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(model4<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02B-Linear_regression---SOLUTIONS_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observations: * Linear regression assumes a normal distribution of residuals * Therefore we want this to be as close to a straight line as possible * Two high median salary outliers appear to be affecting this * We could consider removing these outliers to help build a more reliable model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove highest two median salaries</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>adjusted_graduates <span class="ot">&lt;-</span> graduates <span class="sc">|&gt;</span> </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(Median_salary) <span class="sc">|&gt;</span> </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="fu">nrow</span>(graduates) <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="co"># rerun model</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Median_salary <span class="sc">~</span> Unemployment_rate <span class="sc">+</span> Discipline, </span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>             adjusted_graduates)</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a><span class="co"># test residuals now</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(model5<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02B-Linear_regression---SOLUTIONS_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Healthier looking residual distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view results</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Median_salary ~ Unemployment_rate + Discipline, 
    data = adjusted_graduates)

Residuals:
     Min       1Q   Median       3Q      Max 
-16830.0  -4713.6   -577.4   3618.5  22186.0 

Coefficients:
                                              Estimate Std. Error t value
(Intercept)                                    72367.3     3281.2  22.055
Unemployment_rate                              -1025.4      389.8  -2.630
DisciplineAgriculture &amp; Natural Resources     -13309.9     3454.6  -3.853
DisciplineArts                                -19859.9     3744.8  -5.303
DisciplineBiology &amp; Life Science              -16425.5     3126.5  -5.254
DisciplineBusiness                             -6164.0     3162.5  -1.949
DisciplineCommunications &amp; Journalism         -15779.4     4514.7  -3.495
DisciplineEducation                           -23741.1     3058.1  -7.763
DisciplineEngineering                           8926.5     2761.8   3.232
DisciplineHealth                              -15452.2     3313.7  -4.663
DisciplineHumanities &amp; Liberal Arts           -19168.2     3083.3  -6.217
DisciplineIndustrial Arts &amp; Consumer Services -13721.3     3725.6  -3.683
DisciplineInterdisciplinary                   -21444.3     8077.7  -2.655
DisciplineLaw &amp; Public Policy                 -12609.7     4168.8  -3.025
DisciplinePhysical Sciences                    -4374.8     3372.0  -1.297
DisciplinePsychology &amp; Social Work            -19827.4     3537.0  -5.606
DisciplineSocial Science                      -12409.8     3471.8  -3.574
                                              Pr(&gt;|t|)    
(Intercept)                                    &lt; 2e-16 ***
Unemployment_rate                             0.009400 ** 
DisciplineAgriculture &amp; Natural Resources     0.000171 ***
DisciplineArts                                3.89e-07 ***
DisciplineBiology &amp; Life Science              4.89e-07 ***
DisciplineBusiness                            0.053100 .  
DisciplineCommunications &amp; Journalism         0.000619 ***
DisciplineEducation                           1.07e-12 ***
DisciplineEngineering                         0.001503 ** 
DisciplineHealth                              6.71e-06 ***
DisciplineHumanities &amp; Liberal Arts           4.55e-09 ***
DisciplineIndustrial Arts &amp; Consumer Services 0.000319 ***
DisciplineInterdisciplinary                   0.008771 ** 
DisciplineLaw &amp; Public Policy                 0.002916 ** 
DisciplinePhysical Sciences                   0.196442    
DisciplinePsychology &amp; Social Work            9.34e-08 ***
DisciplineSocial Science                      0.000469 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7705 on 154 degrees of freedom
Multiple R-squared:  0.6957,    Adjusted R-squared:  0.6641 
F-statistic: 22.01 on 16 and 154 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Overall fit has improved, with similar significant variables, but some changes to coefficients.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>